// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var Syntax_Error = /* @__PURE__ */Caml_exceptions.create("Token.Token.Syntax_Error");

function string_of_token(token) {
  if (typeof token !== "number") {
    if (token.TAG === /* String */0) {
      return token._0;
    } else {
      return token._0.toString();
    }
  }
  switch (token) {
    case /* LeftBracket */0 :
        return "}";
    case /* RightBracket */1 :
        return "{";
    case /* Comma */2 :
        return ",";
    case /* Colon */3 :
        return ":";
    case /* True */4 :
        return "true";
    case /* False */5 :
        return "false";
    case /* BackSlash */6 :
        return "\\";
    
  }
}

var Token = {
  Syntax_Error: Syntax_Error,
  string_of_token: string_of_token
};

exports.Token = Token;
/* No side effect */
