// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var Syntax_Error = /* @__PURE__ */Caml_exceptions.create("Token.Syntax_Error");

function toString(token) {
  if (typeof token !== "number") {
    if (token.TAG === /* String */0) {
      return token._0;
    } else {
      return token._0.toString();
    }
  }
  switch (token) {
    case /* LeftSquareBracket */0 :
        return "[";
    case /* RightSquareBracket */1 :
        return "]";
    case /* LeftCurlyBracket */2 :
        return "{";
    case /* RightCurlyBrace */3 :
        return "}";
    case /* Comma */4 :
        return ",";
    case /* Colon */5 :
        return ":";
    case /* True */6 :
        return "true";
    case /* False */7 :
        return "false";
    case /* Null */8 :
        return "null";
    case /* Eof */9 :
        return "eof";
    
  }
}

exports.Syntax_Error = Syntax_Error;
exports.toString = toString;
/* No side effect */
