// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Lexer = require("../src/Lexer.bs.js");

function isValidJson(jsonString) {
  var match = Lexer.scan(jsonString);
  if (match.TAG === /* Ok */0) {
    return true;
  } else {
    return false;
  }
}

describe("Jest", (function () {
        test("can scan a string", (function () {
                return expect(isValidJson("{\n            \"city\" : \"bujumbura\"\n        }")).toBe(true);
              }));
      }));

exports.isValidJson = isValidJson;
/*  Not a pure module */
