// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


describe("Can call the parse method", (function () {
        test("my value should be true", (function () {
                return expect(true).toBe(true);
              }));
      }));

/*  Not a pure module */
